version: "3"

services:
  server:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: quotes-server
  
  client:
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - server
    container_name: quotes-client

  db:
    image: mongo:4
    ports:
      - "27017:27017"
    container_name: quotes-db